[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "usart"
version = "0.1.0"

[dependencies]
heapless = "0.2.1"
aux = { path = "aux" }

[profile.dev]
codegen-units = 1

[profile.release]
debug = true
lto = true
