[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "punch-o-meter"
version = "0.1.0"

[dependencies]
m = "0.1.1"
aux = { path = "aux" }

[profile.dev]
codegen-units = 1

[profile.release]
debug = true
lto = true
